### ISSUE TITLE
org.jetbrains.plugins.terminal.vfs.TerminalSessionEditor cannot be cast to com.intellij.openapi.fileEditor.TextEditor

### ISSUE THREAD

**Issue by Centaur** [whunmr/emacsIDEAs#18]
WebStorm 2016.3

Was doing Ctrl-w Ctrl-q
Looks like the terminal pane is incorrectly recognized as text editor pane.

Detailed call stack:

```
org.jetbrains.plugins.terminal.vfs.TerminalSessionEditor cannot be cast to com.intellij.openapi.fileEditor.TextEditor
java.lang.ClassCastException: org.jetbrains.plugins.terminal.vfs.TerminalSessionEditor cannot be cast to com.intellij.openapi.fileEditor.TextEditor
	at org.hunmr.common.EmacsIdeasAction.collect_active_editors(EmacsIdeasAction.java:90)
	at org.hunmr.common.EmacsIdeasAction.switchEditorIfNeed(EmacsIdeasAction.java:79)
	at org.hunmr.acejump.AceJumpCopyRangeAction.actionPerformed(AceJumpCopyRangeAction.java:23)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.f(IdeKeyEventDispatcher.java:356)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.c(IdeKeyEventDispatcher.java:292)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:217)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by whunmr** [comment]
@Centaur, Thanks for the issue reporting.  
I Just pushed a fix about this issue.
Please try the latest version( 1.4.5) by upgrade.

reopen this issue if it still happens.
